name: Backup automático

on:
  schedule:
    - cron: '0 * * * *'  # Ejecutar cada hora
  workflow_dispatch:      # Permite ejecución manual

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Permite usar git push

      - name: Dar permisos al script
        run: chmod +x scripts/backup_script.sh

      - name: Ejecutar script de backup
        run: ./scripts/backup_script.sh


      - name: Ejecutar script de backup
        run: ./scripts/backup_script.sh
